services:
  db:
    image: postgres:17.6
    environment:
      POSTGRES_USER: investment_user
      POSTGRES_PASSWORD: investment_pass
      POSTGRES_DB: investment_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
