# Generated by Django 5.2.5 on 2025-09-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0002_financialtransaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financialtransaction",
            name="credit",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="financialtransaction",
            name="debit",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
